apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: cat-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cat-service
    spec:
      containers:
      - name: cat-service
        image: gcr.io/feignclientdemo/cat-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1000Mi"
        livenessProbe:
          initialDelaySeconds: 180
          httpGet:
            port: 8081
            path: /actuator/health/liveness
            httpHeaders:
            - name: x-b3-sampled
              value: "0"
        readinessProbe:
          initialDelaySeconds: 40
          httpGet:
            port: 8081
            path: /actuator/health/readiness
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: development